### ISSUE TITLE
[Bug Request]: Local debug New dialog No response after more than two rounds of chat

### ISSUE THREAD

**Issue by SpiderMan95** [239573049/fast-wiki#5]
本地调试ChatModel 跟EmbeddingModel分别用的是百度文心一言的ERNIE-Bot-4和Embedding-V1，创建知识库并导入了一份txt文件量化完成。新建聊天后进行对话。经过多次尝试发现新建对话到第三轮对话时，ai无响应，也没有出现报错。
![1709607326250](https://github.com/239573049/fast-wiki/assets/29696982/9a02c42b-36d9-434d-a735-fe17ea4281c8)

**Comment by 239573049** [comment]
您的知识库的配置是如何配置的，还有您是直接使用文心一言接口 吗？
